apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "alertmanager.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: {{ include "alertmanager.fullname" . }}
        image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
        imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: {{ .Values.alertmanager.image.port }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "alertmanager.fullname" . }}
      - name: alertmanager
        emptyDir: {}
