apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
{{ include "alertmanager.labels" . | indent 4 }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.image.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "alertmanager.name" . }}
