apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.efk.esdata.name }}
spec:
  storageClassName: {{ .Values.efk.esdata.storageClassName }}
  capacity:
    storage: {{ .Values.efk.esdata.storage }}
  accessModes:
    - {{ .Values.efk.esdata.accessModes }}
  hostPath:
    path: {{ .Values.efk.esdata.hostpath }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.efk.esdata.storageClassName }}
{{toYaml .Values.efk.provisioner }}
