apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: grafana
  name: {{ include "grafana.fullname" . }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.image.port }}
  selector:
    k8s-app: {{ include "grafana.fullname" . }}
