apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: parse-server-namespace
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
