apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: parse-server-namespace
  name: mongodb-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local
  volumeName: mongodb-pv
