apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongo-db.fullname" . }}
  labels:
    type: {{ .Values.storage.classname  }}
spec:
  accessModes:
    - {{ .Values.storage.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.storage.size  }}
  storageClassName: {{ .Values.storage.classname }}
  volumeName: {{ include "mongo-db.fullname" . }}
