apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-state-metrics.fullname" . }}-resizer
subjects:
- kind: ServiceAccount
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace:  {{ .Release.Namespace }}
