efk:
  fluentd:
    name: fluentd

    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: v0.12-debian-elasticsearch
      pullPolicy: IfNotPresent

    rules:
    -  apiGroups:
       - ""
       resources:
       - pods
       - namespaces
       verbs:
       - get
       - list
       - watch

  esdata:
    name: es-pv
    claimname: es-pvc
    storageClassName: local
    storage: 10Gi
    accessModes: "ReadWriteOnce"
    hostpath: "/data"

  es:
    name: es-cluster
    replicas: 1
    initImage:
      repository: busybox
      tag: latest
      pullPolicy: IfNotPresent
    Image:
      repository: docker.elastic.co/elasticsearch/elasticsearch-oss
      tag: 6.4.3
      pullPolicy: IfNotPresent


      resources:
        limits:
          cpu: 1000m
        requests:
          cpu: 100m
    env:
      zendiscovery: "es-cluster-0.elasticsearch"
      minimummasternodes: "1"
      ESJAVAOPTS: "-Xms512m -Xmx512m"




  provisioner:
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer
