apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
{{ include "prometheus.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.storage.classname }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessmodes }}
  hostPath:
    path: {{ .Values.storage.hostpath }}
