apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
{{ include "prometheus.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.storage.size  }}
  storageClassName: {{ .Values.storage.classname }}
  volumeName: {{ include "prometheus.fullname" . }}
