replicaCount: 1
image:
  repository: prom/prometheus
  tag: v2.4.3
  pullPolicy: IfNotPresent
  port: 9090
  health_url: /

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

volumemount:
  name: prometheus-storage-volume
  configname: prometheus-config-volume
  rulesname: rules-volume
  mountPath: "/data"
  configPath: "/etc/prometheus/"
  prometheusrulesPath: "/etc/prometheus-rules/"

volumeclaim:
  claimname: prometheus-pvc

storage:
  classname: local
  size: 2Gi
  accessmodes: "ReadWriteOnce"
  hostpath: "/data/prom"

configmap:
  rules_name: prometheus-rules
  prometheus_name: prometheus-server-conf
configmapReload:
  extraArgs{}

server:
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
  configPath: /etc/prometheus/prometheus.yml

service:
  type: LoadBalancer
  port: 9000
